### ISSUE TITLE
Manage sitelinks in google search engine

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#111]
Google search engine displays sitelinks that are not relevant.
![image](https://github.com/StudentTraineeCenter/stcblog/assets/45851215/ebc88d8e-528c-4c8e-9bb3-2bcdef3edb91)

## Notest

- possible source for solution: https://www.reliablesoft.net/sitelinks/

**Comment by petrkucerak** [comment]
I studied this problem. The links are called `sitelinks` and they are chosen automatically by the google algorithm. To remove them is only one solution - add to our site `noindex`. Source google documentation: https://developers.google.com/search/docs/appearance/sitelinks#sitelinks-best-practices. This solution is unacceptable for worsening SEO score in my opinion.
But I can improve the titles of feed pages in the wp template.

**Comment by Vilican** [comment]
Proposing as a won't-fix: solution seems to have a bigger negative impact than the problem.

**Comment by Vilican** [comment]
Closing after consideration as a won't-fix for SEO reasons.
