### ISSUE TITLE
Image sizing problem in feed

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#114]
WordPress 6.7 added a new feature, that adds `loading="lazy"`  for each image without checking if the `height` and `width` is set.
For image responsivity we remove size from image covers: https://github.com/StudentTraineeCenter/stcblog-wp/blob/c06ee660daaf34306a1d513322f1bdc913ad53e5/assets/js/main.js#L100-L102.
It causes problems on Chromium-based browsers.

## Dissucussions

- https://ericportis.com/posts/2023/auto-sizes-pretty-much-requires-width-and-height/
- https://core.trac.wordpress.org/ticket/62413

> Just show that Google chrome adds CSS from browser side. Checked in Version 130.0.6723.117 and 131.0.6778.70 version.
>
> ```php
>img:is([sizes="auto" i], [sizes^="auto," i]) {
>    contain: size !important;
>    contain-intrinsic-size: 300px 150px;
>}
>```
> Do we still needs to add anything from our side?
> If you are having problems with this, soon a new patch will be released.
>
> **Simply by adding**
>```php
><?PHP
>add_filter('wp_img_tag_add_auto_sizes', '__return_false');
> ```
>It will solve the issue.
>
>It's scheduled for next update 6.7.1

## Tasks

- [x] Dockerize WP for local development
- [ ] Solve the problem

**Comment by Vilican** [comment]
@petrkucerak - Note: we can't edit template files. Any modifications need to be release as a separate plugin.
