### ISSUE TITLE
Problem with SyntaxHighlighter Code plugin

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#12]

**Comment by petrkucerak** [comment]
@filiptronicek - The problem is still unresolved. Any ideas?

![image](https://user-images.githubusercontent.com/45851215/95685899-07c54e00-0bfb-11eb-87f6-37602dcdd8fa.png)

**Comment by filiptronicek** [comment]
@petrkucerak it has to be in the encoding/decoding functions of the Syntax highlighter plugin. As per our investigation, that is the only point where this could happen (apart from some db stuff)

**Comment by petrkucerak** [comment]
Problem has been solved removing caching plugin.
