### ISSUE TITLE
Visually differentiate pinned posts

### ISSUE THREAD

**Issue by Vilican** [MicrosoftSTC/stcblog#13]
Pinned posts as they are now, always stick at the top. However, the user who doesn't check posts below (including myself) can easily get tricked into believing it's the latest published post. Therefore, he can miss new posts.

I propose that we add light yellow background _(design for discussion)_ to visually differentiate such sticky posts so users can more easily understand it's pinned there.

**Comment by petrkucerak** [comment]
Ok. That makes sense.
But to be honest, I don't really know if yellow color is right way.

What do you think about other designs?

1) grey background
![image](https://user-images.githubusercontent.com/45851215/94596244-2b4bd880-028c-11eb-8109-79ef7c8efa9a.png)

2) yelow background
![image](https://user-images.githubusercontent.com/45851215/94596440-6817cf80-028c-11eb-8d7d-7753caa778a3.png)

3) some border
![image](https://user-images.githubusercontent.com/45851215/94596858-0a37b780-028d-11eb-8a21-935d5d7a4ecc.png)

4) or this style
![image](https://user-images.githubusercontent.com/45851215/94597201-8fbb6780-028d-11eb-8fce-ebff8f7ab2c9.png)
![image](https://user-images.githubusercontent.com/45851215/94597246-9f3ab080-028d-11eb-9e0a-f23b719b8fcb.png)

**Comment by Vilican** [comment]
@petrkucerak - Yellow backgroud was just a proposal. For me, grey color is used for disabled and outdated things, so we shouldn't use it for important pinned posts. However, I agree that yellow is just as bad. Borders do not clearly convey the message of sticky post.

Maybe we could add a small, but visible pin to upper right corner?

Example:

![image](https://user-images.githubusercontent.com/11300407/94600815-c34cc080-0292-11eb-8f38-a8f146b7f6d2.png)

**Comment by filiptronicek** [comment]
We could use the same pin that GitHub uses (in the Fluent Design icon system)
![image](https://user-images.githubusercontent.com/29888641/95469140-9332ab00-097f-11eb-854b-fa868070fe39.png)

From @petrkucerak's proposals, I like number 4 the most. It's not visually intriguing, and quite nice to look at. At the same time it is very much visible.

**Comment by Vilican** [comment]
@filiptronicek - This pin is fine. We could use it with the 4th (vertical) line design. What do you think?

**Comment by filiptronicek** [comment]
@Vilican agreed. I will take a look at it today.

**Comment by petrkucerak** [comment]
Please do it! @petrkucerak

**Comment by filiptronicek** [comment]
https://github.com/microsoft/fluentui-system-icons - the MSFT icons

**Comment by petrkucerak** [comment]
@filiptronicek and @kahy9 Do you have any idea, where I should place the pinned icon in phone view? 
![image](https://user-images.githubusercontent.com/45851215/107648118-38d28f80-6c7c-11eb-952e-44d28e519c78.png)

I place icon on right top side in PC view mode
![image](https://user-images.githubusercontent.com/45851215/107648480-abdc0600-6c7c-11eb-9ea4-7f25eeb52bc3.png)

**Comment by filiptronicek** [comment]
What about putting it alongside the article title on mobile? @petrkucerak

**Comment by Elesaa** [comment]
We currently have two options - one with only pin icon, second with a colorful badge with intriguing text (for example "TOP").
MarCom graphics will help decide on the final product. After that we put it in use.

**Comment by petrkucerak** [comment]
![image](https://user-images.githubusercontent.com/45851215/107978379-f29f6800-6fbc-11eb-987e-58f29ccdeb66.png)
