### ISSUE TITLE
User's avatar not showing equaly sized

### ISSUE THREAD

**Issue by Vilican** [MicrosoftSTC/stcblog#14]
Size of user's profile pictures are not equal in some posts.

Example post: https://studuj.digital/2021/01/06/jak-naucit-chatbota-lidske-reci/

**Comment by filiptronicek** [comment]
This is due to the images being stored in different sizes and not having any CSS constraints. It's as simple as setting a static height or width to the avatar. 
![screenshot](https://user-images.githubusercontent.com/29888641/107263298-ddb55880-6a41-11eb-91e6-96944845bc5d.png)
