### ISSUE TITLE
Add STC LinkedIn page to social media links

### ISSUE THREAD

**Issue by Vilican** [MicrosoftSTC/stcblog#18]
Add STC LinkedIn page to social media links:
![image](https://user-images.githubusercontent.com/11300407/94378327-186cc300-0129-11eb-87d5-f9543726cdd8.png)

_For discussion - is it meaningful for visitors?_

**Comment by filiptronicek** [comment]
It seems to me like a nice addition, but I would argue, that our focus group isn't interested in LinkedIn that much 🤔

**Comment by Vilican** [comment]
It's probably up to MarCom Team to assess (@irenaandraskova, @nowheretime).

**Comment by Vilican** [comment]
Not required, per response from MarCom Team.
