### ISSUE TITLE
Hamburger menu - phone

### ISSUE THREAD

**Issue by Elesaa** [MicrosoftSTC/stcblog#38]
Hamburger menu on phone not working properly. Won't open on different page than main page.

**Comment by filiptronicek** [comment]
Seems like a problem with the event listener in JS, it's not loading the function in main.js
https://github.com/MicrosoftSTC/stcblog/blob/df45a8d122f565218d29c4eabe64b3987c9ffe11/assets/js/main.js#L57-L62

**Comment by petrkucerak** [comment]
Problem is somewhere in this function

Could you repair it @filiptronicek, please?

> https://github.com/MicrosoftSTC/stcblog/blob/df45a8d122f565218d29c4eabe64b3987c9ffe11/assets/js/main.js#L190-L208
