### ISSUE TITLE
Upgrade to PHP 4.9

### ISSUE THREAD

**Issue by filiptronicek** [MicrosoftSTC/stcblog#4]
Upgrade PHP version when deploying using Azure pipelines to the latest version, [7.4.10](https://www.php.net/archive/2020.php#2020-09-03-2).

Mentioned here:
https://github.com/MicrosoftSTC/stcblog/blob/3152cc18e8dd3a281d9af51451dd5bcf05628eaa/azure-pipelines.yml#L13

**Comment by Vilican** [comment]
@filiptronicek - Why upgrade to PHP 4.9? Azure Pipelines are using v7.2 and hosting is at v7.4

**Comment by filiptronicek** [comment]
@Vilican  Probably for consistency sake. It should be like this is to keep up with the hosting, as to not fail because of stuff introduced in 7.3/4. Nonetheless it's a low priority. Agreed

**Comment by Vilican** [comment]
@filiptronicek - Okay, but I still don't see the point of updating or adding PHP 4.9 - this version is obsolete a we're not using it anyway.
