### ISSUE TITLE
Microsoft Clarity runs before consent

### ISSUE THREAD

**Issue by Vilican** [MicrosoftSTC/stcblog#44]
Microsoft Clarity now runs regardless of consent in cookie notice. Clarity may only run if the user consents to **all** tracking.
Note: if the user disabled optional tracking, Clarity must be disabled too.

**Comment by filiptronicek** [comment]
I would really like to take on the issue, but I think I haven't grasped the idea of enabling/disabling the cookie services, is there any script or code that does this?

**Comment by petrkucerak** [comment]
@filiptronicek

- [https://github.com/nicholasruggeri/cookies-enabler](https://github.com/nicholasruggeri/cookies-enabler)

- https://github.com/MicrosoftSTC/stcblog/blob/bb4263082af58a6e3545868e2df276b0fa6148d7/assets/js/cookies-setting.js#L1-L43

- https://github.com/MicrosoftSTC/stcblog/blob/bb4263082af58a6e3545868e2df276b0fa6148d7/assets/js/cookies-enabler.min.js#L1

**Comment by filiptronicek** [comment]
Thanks @petrkucerak, but I still don't know how the JavaScript could be blocking the loading of GA and others, when JS runs after all these are already loaded.

**Comment by Vilican** [comment]
@filiptronicek - From plugin documentation:

```
**Blocking Cookies from Script Tags**

Add the class "ce-script" and type="text/plain" to every script tag that installs cookies

<script type="text/plain" class="ce-script">
    // GA Demo
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-XXXXX-X']);
    _gaq.push(['_trackPageview']);
</script>

<script type="text/plain" class="ce-script">
    // FB Share Demo
    (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
</script>
```

Basically, it declares the scripts as plaintext (not executable) and marks them with custom class, so it can find them later.
When they are to be activated, it replaces text/plain with script type and the browser executes them.

**Comment by filiptronicek** [comment]
Thanks, @Vilican, I'll see what I can come up with.

**Comment by filiptronicek** [comment]
Well, this could be a problem:
https://github.com/MicrosoftSTC/stcblog/blob/bb4263082af58a6e3545868e2df276b0fa6148d7/footer.php#L75-L77
https://github.com/MicrosoftSTC/stcblog/blob/bb4263082af58a6e3545868e2df276b0fa6148d7/footer.php#L59-L60

I think we should not include these, the user will be tracked even without giving consent with JS turned off (e.g. with Tor)

**Comment by filiptronicek** [comment]
> 
> 
> Well, this could be a problem:
> 
> https://github.com/MicrosoftSTC/stcblog/blob/bb4263082af58a6e3545868e2df276b0fa6148d7/footer.php#L75-L77
> 
> https://github.com/MicrosoftSTC/stcblog/blob/bb4263082af58a6e3545868e2df276b0fa6148d7/footer.php#L59-L60
> 
> I think we should not include these, the user will be tracked even without giving consent with JS turned off (e.g. with Tor)
cc @Vilican
