### ISSUE TITLE
Title of tag page on mobile (IPhone SE2)

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#46]
![image](https://user-images.githubusercontent.com/45851215/102010698-0a017100-3d40-11eb-9f07-cc8f12ee6a5f.png)

**Comment by filiptronicek** [comment]
@petrkucerak can you post the affected URL? This seems to be an error with too long strings to display correctly, the only option would be to size down the font. From my testings on the SE 2020, all the longer titles are showing the way they should. 
![screenshot from the iPhone](https://user-images.githubusercontent.com/29888641/102011461-92821080-3d44-11eb-9de6-fc040cda46b9.png)

Tested on:
- iPhone SE 2020 (750 x 1334 [16:9])
- iOS 13
- Safari browser

**Comment by petrkucerak** [comment]
@filiptronicek problem is combination h1 title with long name of tag.
In my case it is on the page [https://studuj.digital/tag/machinelearningstudio/](https://studuj.digital/tag/machinelearningstudio/)

I think that we can solved it by add something like _word-break_.

**Comment by filiptronicek** [comment]
Oh, I see what you mean there, it seems `word-break: break-all;` really does fix this.
![Screenshot from Firefox mobile simulator](https://user-images.githubusercontent.com/29888641/102063708-a9813b00-3df6-11eb-8ee6-b8ead6d84854.png)

I have created #48 to adress this issue.
