### ISSUE TITLE
Error display letters ě ř

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#5]
![image](https://user-images.githubusercontent.com/45851215/93225606-b13b3000-f772-11ea-8909-0bc0a17d726c.png)

**Comment by filiptronicek** [comment]
Seems pretty platform-specific, works fine on Firefox 82, Win 10
![screenshot of letter display](https://user-images.githubusercontent.com/29888641/94568439-c46af700-026c-11eb-9219-80dc8f962e81.png)

**Comment by filiptronicek** [comment]
@petrkucerak may you please provide the environment details? It looks like a non-Chrome browser on Android, but no further details. I will need that to reproduce this issue if it's not just a rendering bug.

**Comment by petrkucerak** [comment]
non relevant problem
