### ISSUE TITLE
Problem with multiauthors

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#6]
Bad name in tab
![image](https://user-images.githubusercontent.com/45851215/93226125-45a59280-f773-11ea-8043-4c766aaace0d.png)

**Comment by filiptronicek** [comment]
This seems not to be the case anymore, can you provide further details where this happens?

**Comment by filiptronicek** [comment]
Ok, looks like this is still the case, it is probably messed up in the database
![image](https://user-images.githubusercontent.com/29888641/107849778-d1dce400-6dfd-11eb-85b1-9cd0f6443e80.png)
![image](https://user-images.githubusercontent.com/29888641/107849784-d7d2c500-6dfd-11eb-8f03-15f021f3f23e.png)

**Comment by petrkucerak** [comment]
The problem has been solved by reinstall the wp and the new installation plugin.
