### ISSUE TITLE
Block editor throws JSON error

### ISSUE THREAD

**Issue by filiptronicek** [MicrosoftSTC/stcblog#73]
Made a post, saved a draft, got an error:
![image](https://user-images.githubusercontent.com/29888641/115580776-b1cb1480-a2c7-11eb-9af4-b5ed581a7e45.png)
Expectation: JSON
Reality: HTML :(
![image](https://user-images.githubusercontent.com/29888641/115580904-d1fad380-a2c7-11eb-8f08-5d4ef1602749.png)

This is a sad moment for all of us, nonetheless, below are referenced some similar issues which might come in handy:
https://wordpress.org/support/topic/block-editor-show-error-message-that-javascript-is-required/
https://wpml.org/forums/topic/block-editor-shows-error-message-that-javascript-is-required/

**Comment by Vilican** [comment]
@petrkucerak - What's the progress of this issue from your team?

**Comment by petrkucerak** [comment]
The problem causes by the WP External Links plugin. I solved it. More information in this article: https://wordpress.org/support/topic/unexpected-end-of-json-input-4/
![image](https://user-images.githubusercontent.com/45851215/132136260-52271585-0865-4586-b661-462fc6010fa3.png)
