### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#8]

**Comment by filiptronicek** [comment]
I would add colors from https://developer.microsoft.com/en-us/fluentui#/styles/web/colors/products

Skype seems to have similar colors to our blog:
![color pallet of Skype dark mode](https://user-images.githubusercontent.com/29888641/94567833-2b3be080-026c-11eb-8e1e-a64783d6f163.png)

**Comment by filiptronicek** [comment]
All the customizations will be done here: (for reference)
https://github.com/MicrosoftSTC/stcblog/blob/3152cc18e8dd3a281d9af51451dd5bcf05628eaa/assets/scss/_variables.scss#L33-L39

**Comment by filiptronicek** [comment]
We could use https://github.com/GoogleChromeLabs/dark-mode-toggle to toggle the themes @kahy9

**Comment by petrkucerak** [comment]
The dark mode ins't priority, now.
