### ISSUE TITLE
Auto add text when someone copy the text from studuj.digital blog

### ISSUE THREAD

**Issue by petrkucerak** [MicrosoftSTC/stcblog#9]

**Comment by Vilican** [comment]
I advise against implementing this. You probably won't be adding standardized citation after the copied text and besides, the citation requirements vary over institutions.

I've seen this on a few sites and I get quite angry when I try to copy something, paste it into search engine and then realize there's something added.

Does it really give something substantial worth either for us or for our visitors?

**Comment by Vilican** [comment]
Closed as unnecessary
