### ISSUE TITLE
Different content width of articles

### ISSUE THREAD

**Issue by Vilican** [MicrosoftSTC/stcblog#96]
The width of all articles is not the same. Example:

[https://studuj.digital/2022/03/17/excel-a-jeho-vyuziti-ve-stredoskolske-matematice-1-dil/](https://studuj.digital/2022/03/17/excel-a-jeho-vyuziti-ve-stredoskolske-matematice-1-dil/)
![image](https://user-images.githubusercontent.com/11300407/159009538-3858c124-1eb1-4830-a1f6-4c45b0569df3.png)

[https://studuj.digital/2021/07/07/predstavujeme-windows-11/](https://studuj.digital/2021/07/07/predstavujeme-windows-11/)
![image](https://user-images.githubusercontent.com/11300407/159009581-8f31604e-f313-47a3-bdf8-95ebc9ac3206.png)

**Comment by petrkucerak** [comment]
The problem is probably caused by images.

**Comment by petrkucerak** [comment]
The uploading correct image format has solved this problem successfully.
